# >>> intelligent-terminal shell-integration >>>
# Auto-generated by Intelligent Terminal. Do not edit between markers.
# Documents is resolved at runtime so this survives OneDrive Known
# Folder Move and is a silent no-op on machines without IT installed.
$__it_si = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'WindowsPowerShell\shell-integration_v1.ps1'
if (Test-Path -LiteralPath $__it_si) { . $__it_si }
Remove-Variable __it_si -ErrorAction SilentlyContinue
# <<< intelligent-terminal shell-integration <<<
